Controllers/AdminController.cs
using BarberRatingSystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Linq;
using BarberRatingSystem.Models;
using Microsoft.Identity.Client;

namespace BarberRatingSystem.Controllers
{
    public class AdminController : Controller
    {

        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("RoleId") != 2)
            {
                return RedirectToAction("Login", "Account");
            }
            

                var userCount = _context.Users.Count();
            var barberCount = _context.Barbers.Count();
            var reviewCount = _context.Reviews.Count();

            ViewBag.UserCount = userCount;
            ViewBag.BarberCount = barberCount;
            ViewBag.ReviewCount = reviewCount;

            return View();
        }

        public IActionResult Users()
        {
            if (HttpContext.Session.GetInt32("RoleId") != 2)
            {
                return RedirectToAction("Login", "Account");
            }

            var users = _context.Users
            .Select(u => new
            {
                u.Id,
                u.UserName,
                u.FirstName,
                u.LastName,
            }).ToList();

            ViewBag.Users = users;

            return View();
        }


        public IActionResult CreateUser()
        {
            ViewBag.Roles = _context.Roles.ToList();
            return View();
        }

        public IActionResult CreateUser(User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = BCrypt.Net.BCrypt.HashPassword(user.Password);
                _context.Users.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Users");
            }

            ViewBag.Roles = _context.Roles.ToList();
            return View(user);
        }

        public IActionResult EditUser(int id)
        {
            var user = _context.Users.Find(id);
            if (user == null)
            {
                return NotFound();

            }
            ViewBag.Roles = _context.Roles.ToList();
            return ViewBag(user);

        }
        [HttpPost]
        public IActionResult EditUser(User updatedUser)
        {
            var user = _context.Users.Find(updatedUser.Id);
            if (user == null)
            {
                return NotFound();
            }

            user.FirstName = updatedUser.FirstName;
            user.LastName = updatedUser.LastName;
            user.RoleId = updatedUser.RoleId;

            _context.SaveChanges();
            return RedirectToAction("Users");

        }
        public IActionResult DeleteUser(int id)
        {

            var user = _context.Users.Find(id);
            if (user == null)

            {
                return NotFound();
            }
            _context.Users.Remove(user);
            _context.SaveChanges();

            return RedirectToAction("Users");


        }

        public IActionResult Barbers()
        {
            if (HttpContext.Session.GetInt32("RoleId") != 2)
            {
                return RedirectToAction("Login", "Account");

            }
            var barbers = _context.Barbers.ToList();
            return View(barbers);
        }

        public IActionResult CreateBarber()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateBarber(Barber barber, IFormFile Photo)
        {
            
            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    var fileName = Guid.NewGuid() + System.IO.Path.GetExtension(Photo.FileName);
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", fileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        Photo.CopyTo(stream);
                    }

                    barber.PhotoPath = fileName;
                    ;
                }

                _context.Barbers.Add(barber);
                _context.SaveChanges();
                return RedirectToAction("Barbers");
            }
            else return View(barber);
        }
        [HttpGet]
        public IActionResult EditBarber(int id)
        {
            var barber = _context.Barbers.Find(id);
            if (barber == null)
            {
                return NotFound();
            }
            else
            {
                return View(barber);
            }
        }

        [HttpPost]
        public IActionResult EditBarber(Barber updated, IFormFile Photo)
        {
            var barber = _context.Barbers.Find(updated.Id);
            if (barber == null)
            {
                return NotFound();

            }
            barber.Name = updated.Name;
            barber.Description = updated.Description;

            if (Photo != null && Photo.Length > 0)
            {
                var fileName = Guid.NewGuid() + System.IO.Path.GetExtension(Photo.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", fileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    Photo.CopyTo(stream);
                }
                barber.PhotoPath = fileName;
            }
            _context.SaveChanges();
            return RedirectToAction("Barbers");
        }

        public ActionResult DeleteBarber(int id)
        {
            var barber = _context.Barbers.Find(id);
            if (barber != null)
            {
                _context.Barbers.Remove(barber);
                _context.SaveChanges();
                return RedirectToAction("Barbers");
            }

            else
            {
                return NotFound();
            }
        }
        
    }
}

Controllers/ReviewController.cs
using BarberRatingSystem.Data;
using BarberRatingSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace BarberRatingSystem.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReviewController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpPost]
        public IActionResult Add(int BarberId, string Text)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var review = new Review()
            {
                UserId = userId.Value,
                BarberId = BarberId,
                Text = Text,
                DateTime = DateTime.Now
            };

            _context.Reviews.Add(review);
            _context.SaveChanges();

            return RedirectToAction("Details", "Barber", new { id = BarberId });
        }

        public IActionResult MyReviews()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }
            var reviews = _context.Reviews
            .Where(r => r.UserId == userId)
            .Select(r => new
            {
                r.Id,
                r.Text,
                r.DateTime,
                BarberName = r.Barber.Name

            })
            .ToList();
            ViewBag.MyReviews = reviews;
            return View();
        }

        public IActionResult Edit(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            var review = _context.Reviews.FirstOrDefault(r => r.Id == id && r.UserId == userId);
            if (review == null)
            {
                return NotFound();
            }
            return View(review);
        }
        [HttpPost]
        public IActionResult Edit(Review updatedReview)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            var review = _context.Reviews.FirstOrDefault(r => r.Id == updatedReview.Id && r.UserId == userId);
            if (review == null)
            {
                return NotFound();
            }
            review.Text = updatedReview.Text;
            _context.SaveChanges();

            return RedirectToAction("MyReviews");
        }

        public IActionResult Delete(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            var review = _context.Reviews.FirstOrDefault(r => r.Id == id && r.UserId == userId);
            if (review != null)
            {
                _context.Reviews.Remove(review);
                _context.SaveChanges();
            }

            return RedirectToAction("MyReviews");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BarberRatingSystem</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/BarberRatingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BarberRatingSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <nav>

        <a asp-controller="Home" asp-action="Index">Home</a>
        @if(Context.Session.GetString("Username") != null)
        {
            <a asp-controller="Account" asp-action="Logout">Logout (@Context.Session.GetString("Username"))</a>
            if (Context.Session.GetString("RoleId") == "2")
            {
                <a asp-controller="Admin" asp-action="Index">Admin Dashboard</a>
            }
            else
            {
                <a asp-controller="Review" asp-action="MyReview">My Reviews</a>
            }
        }
        else
        {
        }

        @if (Context.Session.GetInt32("UserId") != null)
        {
            <a asp-controller="Account" asp-action="Logout">Logout</a>
        }
        @if (Context.Session.GetInt32("UserId") == null)
        {
            <a asp-controller="Account" asp-action="Login">Login</a>
            <a asp-controller="Account" asp-action="Register">Register</a>
        }
    </nav>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - BarberRatingSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</body>
</html>